services:
  postgres:
    image: postgres:16-alpine
    container_name: devsu-postgres
    environment:
      POSTGRES_USER: devsu
      POSTGRES_PASSWORD: devsu
      POSTGRES_DB: cliente_db          # cuenta_db se crea con el init script
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsu"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: devsu-rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # consola de gestión
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  cliente-service:
    build:
      context: .
      dockerfile: cliente-service/Dockerfile
    container_name: devsu-cliente-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cliente_db
      DB_USER: devsu
      DB_PASSWORD: devsu
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      API_KEY: ${API_KEY:-devsu-secret-key}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

  cuenta-service:
    build:
      context: .
      dockerfile: cuenta-service/Dockerfile
    container_name: devsu-cuenta-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cuenta_db
      DB_USER: devsu
      DB_PASSWORD: devsu
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      API_KEY: ${API_KEY:-devsu-secret-key}
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

  dashboard:
    build:
      context: ./dashboard
    container_name: devsu-dashboard
    ports:
      - "8080:80"
    depends_on:
      - cliente-service
      - cuenta-service

volumes:
  postgres-data:
